Repository witseie-elen4010/2022-group-lab-017, pull requests merged in 2022-05, with the labels that each got.

#14 Created Sign-in and Sign-up pages
  .vscode/settings.json
  Public/css/keyboard.css
  Public/css/login_page.css
  Public/css/main.css
  Public/scripts/scripts.js
  Public/templates/keyboard.html
  index.html
  index.js
  login.css
  login.js
  package-lock.json
  package.json
  scripts.js
Labels: enhancement

#16 keyboard handling code
  Project_code/scripts.js
Labels: enhancement

#15 Empty folders
  .gitkeep
  Project_code/Backend/mainRoutes.js
  Project_code/public/scripts/index.js
  Project_code/views/about.html
Labels: duplicate

#17 Modifications to folder structure and code for sign-in and sign-up
  Project_code/public/css/keyboard.css
  Project_code/public/css/signin_signup.css
  Project_code/public/scripts/index.js
  Project_code/public/scripts/scripts.js
  Project_code/public/scripts/words.js
  Project_code/views/keyboard.html
  Project_code/views/signup.html
  Public/css/login_page.css
  Public/css/main.css
  Public/scripts/scripts.js
  index.html
  login.css
  login.js
Labels: enhancement

#18 Added Routing
  Project_code/Backend/mainRoutes.js
  Project_code/views/signup.html
  index.html
  index.js
  package.json
Labels: enhancement

#19 My work thabang2
  Project_code/public/css/style.css
  Project_code/public/image/backg.jpg
  Project_code/public/scripts/scripts.js
  Project_code/views/game.html
  Project_code/views/keyboard.html
  index.html
Labels: enhancement

#20 Linking Login Page to Game page
  Project_code/Backend/mainRoutes.js
  Project_code/public/css/signin_signup.css
  Project_code/public/css/style.css
  Project_code/public/scripts/scripts.js
  Project_code/views/game.html
  index.html
Labels: enhancement

#34 Sprint 2 start
  Documentation/Sprint 2/Retrospective/Sprint_1_retrospective
  Documentation/Sprint 2/ScrumBoard at Start/ScrumBoard Start_1.png
  Documentation/Sprint 2/ScrumBoard at Start/ScrumBoard Start_2.png
  Documentation/Sprint 2/ScrumBoard at Start/ScrumBoard Start_3.png
  Documentation/Sprint 2/ScrumBoard at Start/ScrumBoard Start_4.png
Labels: enhancement

#35 Tracking number of connectors to server and changing between gamestates
  .vscode/settings.json
  Project_code/Backend/mainRoutes.js
  Project_code/public/scripts/gameStates.js
  Project_code/public/scripts/scripts.js
  index.html
  index.js
  package-lock.json
  package.json
Labels: bug, help wanted

#36 Added a Main Menu for choosing between player modes
  Project_code/Backend/mainRoutes.js
  Project_code/public/css/main_menu.css
  Project_code/views/main_menu.html
  index.html
Labels: enhancement

#37 Choosing Two-Player Mode
  Project_code/Backend/mainRoutes.js
  Project_code/public/css/invite_player.css
  Project_code/public/css/signin_signup.css
  Project_code/views/invite_player.html
  Project_code/views/invite_two_players.html
  Project_code/views/main_menu.html
Labels: enhancement

#39 Life
  Project_code/public/css/style.css
  Project_code/public/scripts/scripts.js
  Project_code/views/game.html
  package-lock.json
  package.json
Labels: enhancement, User Story

#42 added oppenent game board
  Project_code/public/css/invite_player.css
  Project_code/public/css/style.css
  Project_code/public/scripts/game_2.js
  Project_code/views/game_2.html
  Project_code/views/invite_player.html
  Project_code/views/main_menu.html
Labels: enhancement

#43 Added an invite feature for two player mode
  Project_code/public/css/invite_player.css
  Project_code/public/scripts/invite_player.js
  Project_code/views/invite_player.html
Labels: enhancement

#44 Modiffied the invite feature
  Project_code/Backend/mainRoutes.js
  Project_code/public/css/invite_player.css
  Project_code/public/scripts/invite_player.js
  Project_code/views/invite_player.html
  Project_code/views/main_menu.html
Labels: enhancement

#45 issue10
  Project_code/public/scripts/scripts.js
Labels: User Story

#46 End of Sprint 2
  Documentation/Sprint 2/ScrumBoard at End/ScrumBoard_end_1.png
  Documentation/Sprint 2/ScrumBoard at End/ScrumBoard_end_2.png
  Documentation/Sprint 2/ScrumBoard at End/ScrumBoard_end_3.png
  Documentation/Sprint 2/ScrumBoard at End/ScrumBoard_end_4.png
Labels: enhancement

#59 checking for working rooms
  Project_code/Backend/sever.js
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/invite_player.js
  Project_code/public/scripts/scripts.js
  Project_code/public/scripts/users.js
  Project_code/views/game_2.html
  index.js
  package-lock.json
  package.json
Labels: bug

#61 3-player-mode and backend sign-in-sign-up
  Project_code/Backend/Configs/db.js
  Project_code/Backend/Controllers/userAccount.js
  Project_code/Backend/Routes/mainRoutes.js
  Project_code/Backend/Routes/userAccount.js
  Project_code/Backend/mainRoutes.js
  Project_code/public/css/invite_two_players.css
  Project_code/public/css/signin_signup.css
  Project_code/public/scripts/invite_two_players.js
  Project_code/views/invite_two_players.html
  Project_code/views/main_menu.html
  Project_code/views/signup.html
  index.html
  index.js
  package-lock.json
  package.json
Labels: enhancement

#62 End of sprint 3
  .idea/.gitignore
  .idea/2022-group-lab-017.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/modules.xml
  .idea/vcs.xml
  Documentation/Sprint 3/scrumBoard at end/Screenshot (11) - Copy.png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (12).png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (13).png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (14).png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (15).png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (16).png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (17).png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (18).png
  Documentation/Sprint 3/scrumBoard at end/Screenshot (19).png
  Project_code/Backend/sever.js
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/scripts.js
  Screenshot (11).png
  index.js
Labels: documentation
