Repository witseie-elen4010/2022-group-lab-017, pull requests merged in 2022-06, with the labels that each got.

#63 2 player game updates
  Project_code/public/css/style.css
  Project_code/public/scripts/game_2.js
  Project_code/views/game_2.html
  index.js
  package-lock.json
  package.json
Labels: enhancement

#72 three players functionality
  Project_code/Backend/Routes/mainRoutes.js
  Project_code/public/css/style.css
  Project_code/public/scripts/game_3.js
  Project_code/views/game_3.html
  Project_code/views/main_menu.html
  index.js
Labels: enhancement

#73 board hearders
  Project_code/public/scripts/game_3.js
  Project_code/views/game_3.html
Labels: enhancement

#74 fixed two player functionality
  Project_code/public/css/style.css
  Project_code/public/scripts/game_2.js
  Project_code/views/game_2.html
  index.js
Labels: enhancement

#75 Words branch
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  index.js
Labels: enhancement, epic

#76 opponent wining alerts
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  index.js
Labels: enhancement

#77 Added User Cookies and Protected all Routes
  Documentation/Sprint 3/scrumBoard at end/Screenshot (11).png
  Documentation/Sprint 4/Retrospective/Sprint_3_retrospective.md
  Documentation/Sprint 4/ScrumBoard at Start/ScrumBoard Start_1.png
  Documentation/Sprint 4/ScrumBoard at Start/ScrumBoard Start_2.png
  Documentation/Sprint 4/ScrumBoard at Start/ScrumBoard Start_3.png
  Documentation/Sprint 4/ScrumBoard at Start/ScrumBoard Start_4.png
  Documentation/Sprint 4/ScrumBoard at Start/ScrumBoard Start_5.png
  Documentation/Sprint 4/ScrumBoard at Start/ScrumBoard Start_6.png
  Project_code/Backend/Controllers/userAccount.js
  Project_code/Backend/Routes/mainRoutes.js
  Project_code/Backend/Routes/userAccount.js
  Project_code/views/main_menu.html
  index.html
  index.js
  package-lock.json
  package.json
Labels: enhancement

#78 Alerts
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  package-lock.json
  package.json
Labels: enhancement

#79 changes
  Project_code/public/css/style.css
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  Project_code/views/game_2.html
  Project_code/views/game_3.html
  index.js
Labels: enhancement

#80 Kevy branch
  Project_code/public/scripts/game_3.js
  Project_code/views/game_3.html
  index.js
Labels: enhancement

#81 Kevy branch
  Project_code/public/scripts/game_3.js
  Project_code/views/game_3.html
  index.js
Labels: enhancement

#82 added a port variable
  Project_code/public/css/style.css
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  Project_code/views/game_2.html
  Project_code/views/game_3.html
  index.js
Labels: enhancement

#83 jest setting
  Project_code/public/css/style.css
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  Project_code/tests/game.js
  Project_code/views/game_2.html
  index.js
  package-lock.json
  package.json
Labels: testing

#84 Log2
  Project_code/public/css/style.css
  Project_code/public/scripts/game_3.js
  Project_code/public/scripts/scripts.js
  Project_code/tests/scripts.test.js
  package.json
Labels: enhancement, help wanted

#86 non empty form submision feature
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  package-lock.json
  package.json
Labels: enhancement

#89 Fixed the placeholder error
  index.html
Labels: bug

#90 Added missing testcase dependencies
  Project_code/__tests__/game.js
  Project_code/__tests__/scripts.test.js
  package-lock.json
  package.json
Labels: bug

#92 Added one sample testcase
  Project_code/__tests__/game.js
  Project_code/__tests__/scripts.test.js
  Project_code/__tests__/sum.test.js
Labels: bug

#94 Fixing deployment with jest coverage
  package.json
Labels: bug, testing

#95 Code refactoring
  Project_code/Backend/Controllers/userAccount.js
  Project_code/public/scripts/game_3.js
  index.html
Labels: enhancement

#97 Azure bug
  Project_code/public/scripts/game_3.js
  Project_code/views/game_2.html
  Project_code/views/game_3.html
  index.html
  package-lock.json
  package.json
Labels: enhancement

#101 Issues
  Project_code/Backend/Routes/userAccount.js
  Project_code/views/signup.html
Labels: bug, enhancement

#105 Simple testing of functions
  Project_code/__tests__/testingFunctions.spec.js
  Project_code/public/scripts/testingFunctions.js
  package.json
Labels: enhancement, testing

#106 basic functionality tests
  Project_code/__tests__/modelingFunctionalities.test.js
  Project_code/public/scripts/modelingFunctionalities.js
Labels: enhancement, testing

#108 Fixed Sign-up
  Project_code/views/signup.html
Labels: bug

#110 Testing to see if Deployment is fixed
  Project_code/Backend/Routes/userAccount.js
Labels: bug

#111 Added Website URL to Readme
  Documentation/Sprint 3/Retrospective/Sprint_2_retrospective.md
  Documentation/Sprint 3/ScrumBoard at Start/ScrumBoard_start_1.png
  Documentation/Sprint 3/ScrumBoard at Start/ScrumBoard_start_2.png
  Documentation/Sprint 3/ScrumBoard at Start/ScrumBoard_start_3.png
  Documentation/Sprint 3/ScrumBoard at Start/ScrumBoard_start_4.png
  Documentation/Sprint 3/ScrumBoard at Start/ScrumBoard_start_5.png
  Documentation/Sprint 3/ScrumBoard at Start/ScrumBoard_start_6.png
  README.md
Labels: bug

#112 azure fix
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  Project_code/views/game_2.html
  Project_code/views/game_3.html
Labels: bug, enhancement

#113 log functionality
  Project_code/public/css/style.css
  Project_code/public/scripts/game_2.js
  Project_code/public/scripts/game_3.js
  Project_code/views/game_2.html
  Project_code/views/game_3.html
  index.js
Labels: enhancement

#116 End of scrumBoard
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 1 .png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 10.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 11.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 12.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 13.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 14.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 15.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 16.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 17.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 18.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 19.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 2.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 20.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 3.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 4.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 5.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 6.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 7.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 8.png
  Documentation/Sprint 4/scrumBoard_at_End/Screenshot 9.png
Labels: documentation
